sudo: false
dist: trusty
language: python

packages: &build_deps_optional
  - swig
  - libxml2-utils
  - yum
  - libaugeas-dev
  - augeas-lenses
  - libacl1-dev
  - libssl-dev

matrix:
  include:
    - env: PYTHON=2.4 NOSE_EXCLUDE_DIRS=testsuite/Testsrc/Testlib/TestServer
      addons:
        apt:
          sources: [deadsnakes]
          packages: [python2.4, python2.4-dev]
    - env: PYTHON=2.5 NOSE_EXCLUDE_DIRS=testsuite/Testsrc/Testlib/TestServer
      addons:
        apt:
          sources: [deadsnakes]
          packages: [python2.5, python2.5-dev, libbluetooth-dev]

    - python: "2.6"
    - python: "2.6"
      env: WITH_OPTIONAL_DEPS=yes
      addons:
        apt:
          packages: *build_deps_optional

    - python: "2.7"
    - python: "2.7"
      env: WITH_OPTIONAL_DEPS=yes WITH_SYSTEM_SITE_PACKAGES=yes TEST_SPHINX=yes
      addons:
        apt:
          packages: [*build_deps_optional, python-gamin, python-selinux]

    - python: "3.5"
      env: WITH_OPTIONAL_DEPS=yes
      addons:
        apt:
          packages: *build_deps_optional

  allow_failures:
    - python: "3.5"

  fast_finish: true

before_install:
  - testsuite/prepare-python.sh
  - if test -d "$HOME/custom-virtualenv/"; then source "$HOME/custom-virtualenv/bin/activate"; fi
install:
  - testsuite/install.sh
  - pip install -e .
script:
  - testsuite/test.sh
after_failure:
  - pip freeze

branches:
  except:
    - maint-1.2
    - 1.1.0-stable

notifications:
  irc:
    channels:
      - "irc.libera.chat#bcfg2"
    use_notice: true

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/wheels
    - $HOME/.cache/xml

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
  - rm -f $HOME/.cache/xml/catalog.xml
